use_frameworks!

platform :ios, '10.0'

target 'PasseiCircleAnimation_Example' do
  pod 'PasseiCircleAnimation', :path => '../'

  target 'PasseiCircleAnimation_Tests' do
    inherit! :search_paths

    
  end
end
